class test
{
 void m()
 {
  int data=50/0;
 }
 void n()
 {
  m();
 }
 void p()
 {
 try{
  n();
 }
 catch(Exception e)
 {
 System.out.println("exception handled");
 }
 public static void main(String[]args)
 {
   test a = new test();
   a.p();
   System.out.println("Flowers made....");
 } 
} 
/*output
exception handled
Flowers made....
*/
